framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_magento:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                
                # default configuration
                retry_strategy:
                    max_retries: 10
                    # 60 sec delay
                    delay: 60000
                    # causes the delay to be higher before each retry
                    # e.g. 10 second delay, 20 seconds, 40 seconds, 80 seconds
                    #multiplier: 2
                    # e.g. 10 second delay, 10 seconds, 10 seconds, 10 seconds
                    multiplier: 1
                    max_delay: 0
                    # override all of this with a service that
                    # implements Symfony\Component\Messenger\Retry\RetryStrategyInterface
                    # service: null
            
            #External        
            external_magento:
                dsn: '%env(EXTERNAL_MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\ExternalMagentoJsonMessengerSerializer
                options:
                    exchange:
                        type: topic
                    queues:
                        auto_setup: false
                        transactional-email.bloomreach.all: ~                        
                    
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\StatusUpdate': async_magento
            'App\Message\Email': external_magento

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
